name: Update PreMiD Status
on:
  schedule:
    - cron: "*/8 * * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update PreMiD Status
        run: python main.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          FRONTEND_HASH: ${{ secrets.FRONTEND_HASH }}
          DOCS_HASH: ${{ secrets.DOCS_HASH }}
          DL_HASH: ${{ secrets.DL_HASH }}
          CDN_HASH: ${{ secrets.CDN_HASH }}
          API_HASH: ${{ secrets.API_HASH }}
          PD_HASH: ${{ secrets.PD_HASH }}
